#!/bin/bash

if [ ! -f ~/cronLastUpdate ]; then
	`touch ~/cronLastUpdate`
fi

lastUpdate=$(cat ~/cronLastUpdate)
cron=$(md5sum /var/spool/cron/crontabs/vagrant)

if [ "$lastUpdate" != "$cron"  ]; then
	echo "Crontab modified" | mail -s "Contab" root
	`md5sum /var/spool/cron/crontabs/vagrant > ~/cronLastUpdate`
fi